name: Update Links Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Data from Google Sheets
        run: |
          curl -L -o Links_data.csv "https://docs.google.com/spreadsheets/d/13b2eqynihRCuaoyQKeUNct55vwzsg_Xk_JwJ8z3FxAg/export?format=csv"

      - name: Save to GitHub
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Links_data.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "Updated data from Google Sheet" && git push)
          
